### ISSUE TITLE
Weather at night

### ISSUE THREAD

**Issue by Brutuss** [robgeerts/Dashticz#14]
At night when it is clear weather i see a sun chining. Maybe it is possible the make it a moon ;) ?

**Comment by robgeerts** [comment]
I have implemented a possible fix.
Could you let me know if it works? If not, could you give me the text you see in a little popup (title) when you place the mouse on the icon? Thanks!

**Comment by Brutuss** [comment]
I still see the sun and the icon gives a popup called: sunny

**Comment by Brutuss** [comment]
This is also with the icon "Partly Cloudy"

**Comment by robgeerts** [comment]
This is fixed bij adding a dummy-switch in Domoticz with the name 'DayOrNight'.
Add a timer for this switch wich will set the switch ON by sunrise and OFF by sunset.
Finally, add the name of this switch in the settings of Dashticz!

In a future version it won't be needed anymore to add this dummy-switch.
